default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  database: items_app_development
  <<: *default

test:
  database: items_app_test
  <<: *default

production:
  database: items_app_production
  <<: *default